#ifndef ASSIGNMENT3_COMMON_H
#define ASSIGNMENT3_COMMON_H

#define MIN_PORT_VALUE 5000
#define MAX_PORT_VALUE 64000

#define REQUEST_FORMAT "%d %s %d\n"
#define RESPONSE_FORMAT "%d\n"
#define MESSAGE_SIZE 1024

#endif //ASSIGNMENT3_COMMON_H
